name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Define environment variables
    env:
      JAVA_VERSION: "17"
      MAIN_MODULE: "module-c" # The main module for build and tests

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Java environment
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      # Step 3: Build all modules
      - name: Build all modules
        run: mvn -B clean install

      # Step 4: Build and test only the main module
      - name: Test and package the main module
        run: mvn -B -pl ${{ env.MAIN_MODULE }} test package

      # Step 5: Update dependency graph (Optional)
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
